### PR TITLE
Disallow logging time on closed projects; fixes #62

### LINKED ISSUE #62: Disallow logging time on closed projects
**Bug summary**
Redmine doesn't allow creating time entries on closed projects but this plugin is allowing it because there is an access check for admin users that allows it.

**To Reproduce**
1. Close an existing project
2. Track time in Toggl for an issue in the closed project
3. Go to import time in Redmine
4. Select the time entries for the closed project
5. Click Import. It works but it should fail.

**Expected behavior**
Importing time entries on closed projects should not be allowed because they are read-only.

Let me know if you need any more info. I'll provide a PR with what looks to me like a fix.

### PR DESCRIPTION
**Pull request by jigarius**
## The problem

- Users should not be allowed to log time on closed projects.
  - Even admins should be disallowed because that's the behavior we get in the Redmine UI.

## What's done

- Updated fixtures for testing this bug fix.
- Enabled membership and `:log_time` permission test for admin users.
- Fixed one test that was broken due to the change in fixtures.
- The T2R UI prevents users from importing time entries if the associated project is closed.

### CODE REVIEW

File: test/integration/t2r_import_controller_test.rb [hunk 1]
```diff
@@ -96,7 +96,7 @@ def setup
         activity_id: enumerations(:activity_development).id,
         comments: 'Special delivery!',
         hours: 4.0,
-        issue_id: issues(:charlie_001).id,
+        issue_id: issues(:delta_001).id,
```
Comment (jigarius) [inline test/integration/t2r_import_controller_test.rb:99]: J Smith now has access to Project Charlie, so I had to use Project Delta for this test.

File: test/fixtures/issues.yml [hunk 2]
```diff
@@ -1,6 +1,5 @@
 alpha_001:
   subject: 'Abstract apples'
-  description: John Smith is a 'Manager' of project 'Alpha'.
```
Comment (jigarius) [inline test/fixtures/issues.yml:3]: Ignore these one-line removals. I'm removing these redundant descriptions to make the fixture easier to maintain.

File: test/fixtures/projects.yml [hunk 3]
```diff
@@ -17,10 +17,10 @@ bravo:
 charlie:
   identifier: charlie
   name: Project charlie
-  description: John Smith doesn't have access to this project.
+  description: John Smith has 'manager' access to this project, but the project is closed.
   lft: 5
   rgt: 6
-  status: 0
+  status: 5  # Project.STATUS_CLOSED
```
Comment (jigarius) [inline test/fixtures/projects.yml:23]: Turns out `0` doesn't mean project closed. Project closed needs the status `5`. There's a constant `Project.STATUS_CLOSED` that determines whether `project.closed?` returns `true` or `false`.

File: test/integration/t2r_toggl_controller_test.rb [hunk 4]
```diff
@@ -223,7 +223,7 @@ def setup
   end
 
   test ".read_time_entries returns issue as nil when user doesn't belong to the project" do
-    issue = issues(:charlie_001)
+    issue = issues(:delta_001)
```
Comment (jigarius) [inline test/integration/t2r_toggl_controller_test.rb:230]: J Smith now has access to Project Charlie, so I had to use Project Delta for this test.

File: test/integration/t2r_import_controller_test.rb [hunk 5]
```diff
@@ -152,6 +152,27 @@ def setup
...
+      }
+    }
+
+    post '/toggl2redmine/import', params: data
+
+    assert_response 403
+    assert_equal(
+      { 'errors' => ['You are not allowed to log time on this project.'] },
+      @response.parsed_body
+    )
```
Comment (jigarius) [inline test/integration/t2r_import_controller_test.rb:173]: This is the response you'll get if you try to log time on a closed project.

**Review by jigarius — COMMENTED** [review]
I'll wait for Kevin to confirm that these changes work correctly and then merge the changes into master.

**Comment by kporras07** [comment]
@jigarius this works great! Thanks :)
